app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function(){
 
    Route::get('/', [
        'as'    =>  'index.web',
        'uses'  =>  'WebController@index'
    ]);
    
    Route::get("/email", function(){
        return redirect()->away('https://privateemail.com/appsuite');
    });

    Route::get('/welcome','WebController@index');
    Route::post('/welcome','WebController@subscribe');
    Route::resource('/registration','RegistrationController');
    Route::resource('/courses','CourseController');
    Route::post('/gallery',[
        'as'    =>  'gallery.destroy',
        'uses'  =>  'GalleryController@destroy'
    ]);
    Route::resource('/gallery','GalleryController@index',[
        'only'  =>  [
            'index'
        ]
    ]);

    Route::get('/course/{course}',[
        'as'    =>  'course.show',
        'uses'  =>  'CourseController@show'
    ])->middleware(['auth','payed']);
    
    Route::post('/getsector','RegistrationController@getSector');
    Route::get('/getsector',function(){
        return abort(404);
    });
    
    Route::get('/nopayment', [
    	'as'	=>	'nopayment',
    	'uses'	=>	'nopayment@no'
    ]);

    Route::get('/contact-us',[
        'as'    =>  'contact.us.web',
        'uses'  =>  'ContactUsController@getContactUs'
    ]);

    Route::post('/contact-us',[
        'as'    =>  'contact.us.post.web',
        'uses'  =>  'ContactUsController@postContactUs'
    ]);

    Route::get('read/{id}',"CourseController@read");
    Route::get('quiz',[
        'as'    =>  'doquiz',
        'uses'  =>  "QuizController@doQuiz"
    ]);
    Route::post('student/answers', [
        'as'    =>  'submit.answers',
        'uses'  =>  'QuizController@postUserAnswers'
    ]);
    Route::post('quiz',[
        'as'    =>  'next.to.question',
        'uses'  =>  'QuizController@doQuizPostCredit'
    ]);

    Route::get('statistics', [
        'as'    =>  'statistics.show',
        'uses'  =>  'QuizController@statistics'
    ]);

    Route::get('certificates', [
        'as'    =>  'certificates',
        'uses'  =>  'QuizController@certificates'
    ]);

    Route::get('view/{id}/{token}', [
        'as'    =>  'viewcert',
        'uses'   =>  "QuizController@certificate"
    ]);

    Route::get('/{slug}/', [
        'as'    =>  'with.slug.web',
        'uses'  =>  'WebController@staticPage'
    ]);
    
    //Auth Routes
    Route::auth();

    //User Prefix
    Route::group(['prefix' => 'client'],function(){
        
        Route::get('/login',[
            'as'    =>  'login.user',
            'uses'  =>  'Auth\AuthController@getLogin'
        ]);
        
        Route::post('/login',[
            'as'    =>  'post.login.user',
            'uses'  =>  'Auth\AuthController@login'
        ]);
        
        Route::group([ 'namespace' => 'Users', 'middleware' => 'auth' ], function(){
            Route::get('/dashboard',[
                'as'    =>  'dashboard.user',
                'uses'  =>  'UserController@dashboard'
            ]);
            Route::get('/profile', [
                'as'    =>  'profile.user',
                'uses'  =>  'UserController@profile'
            ]);
        });

        Route::get('/logout',[
            'as'    =>  'logout.user',
            'uses'  =>  'Auth\AuthController@logout'
        ]);


    });
    
    
    
    //Admin Route
    

    //Admin Middleware Group
    Route::group([ 'prefix' => 'admin'],function(){
        
        Route::get('/login', [
            'as'    =>  'login.super',
            'uses'  =>  'Auth\SuperController@getLogin'
        ]);
        Route::post('/login',[
            'as'    =>  'login.super',
            'uses'  =>  'Auth\SuperController@login'
        ]);
        //Logout
        Route::get('/logout',[
            'as'    =>  'logout.super',
            'uses'  =>  'Auth\SuperController@logout'
        ]);
        
        Route::group([ 'namespace' => 'Super', 'middleware' => 'admin' ],function(){
            
            
            Route::get('/dashboard', [
                'as'   => 'dashboard.super', 
                'uses' => 'SuperController@getDashboard'
            ]);
            //Users
            Route::get('/profile', [
                'as'    =>  'profile.super',
                'uses'  =>  'SuperController@getProfile'
            ]);
            Route::post('/profile', [
                'uses'    =>    'SuperController@updateProfile',
                'as'      =>    'post.profile.super'
            ]);

            Route::post('/send', [
                'as'    =>  'send.email.super',
                'uses'  =>  'SuperController@sendEmail'
            ]);

            Route::post('/markasread',"SuperController@markAsRead");
            
            Route::resource('subscribes',"SubscribesController",[
                'names' =>  [
                    'index' =>  'subcribes.index'
                ]
            ]);

            /*
                Clients Section    
             */
            Route::group(['prefix' => 'clients'], function(){
                Route::get('/all', 'UsersController@index');
                Route::get('/', [
                    'as'    =>  'all.user.super',
                    'uses'  =>  'UsersController@index'
                ]);
                Route::get('/allowed', [
                    'as'    =>  'allowed.user.super',
                    'uses'  =>  'UsersController@getAllowed'
                ]);
                Route::get('/not-allowed',[
                    'as'    =>  'not.allowed.user.super',
                    'uses'  =>  'UsersController@getNotAllowed'
                ]);
                Route::post('/allow', [
                    'as'    =>  'allow.user.super',
                    'uses'  =>  'UsersController@allow'
                ]);
                Route::get('/add', [
                    'as'    =>  'add.user.super',
                    'uses'  =>  'UsersController@create'
                ]);
                Route::post('/add', [
                    'as'    =>  'save.user.super',
                    'uses'  =>  'UsersController@store'
                ]);
                Route::post('/reverse', [
                    'as'    =>  'reverse.user.super',
                    'uses'  =>  'UsersController@reverseApproval'
                ]);
                Route::post('/',[
                    'as'    =>  'delete.user.super',
                    'uses'  =>  'UsersController@destroy'
                ]);
                Route::get("/{id}", [
                    'as'    =>  'view.user.super',
                    'uses'  =>  'UsersController@show'
                ]);
            });
            /*
                Pages Section    
             */
            Route::group(['prefix' => 'pages' ], function(){
                Route::post('/edit', [
                    'as'    =>  'update.page.super',
                    'uses'  =>  'PagesController@update'
                ]);
                Route::get('/menu', [
                    'as'    =>  'menu.page.super',
                    'uses'  =>  'PagesController@getMenu'
                ]);
                Route::post('/ordermenu', [
                    'as'    =>  'order.menu.super',
                    'uses'  =>  'PagesController@orderMenu'
                ]);
                Route::post('/menu', [
                    'as'    =>  'status.menu.super',
                    'uses'  =>  'PagesController@statusMenu'
                ]);
                Route::get('/static/{id}',[
                    'as'    =>  'static.page.super',
                    'uses'  =>  'StaticController@edit'
                ]);
                Route::post('/static', [
                    'as'    =>  'static.page.super',
                    'uses'  =>  'StaticController@update'
                ]);
                Route::get('/static', function(){
                    abort(404);
                });
                Route::post('/destroy',[
                    'as'    =>  'destroy.page.super',
                    'uses'  =>  'PagesController@destroy'
                ]);

                // Route::get('/edit/{id}', function($id){
                //     return $id;
                // });

            });
            Route::resource('pages', 'PagesController', [
                'names' =>  [
                    'index'     =>  'all.pages.super',
                    'create'    =>  'create.page.super',
                    'store'     =>  'store.page.super',
                    'edit'      =>  'edit.page.super'
                ],
                'only'  =>  [
                    'index','show', 'edit','create','store'
                ]
            ] );
            /*
                Sub-Pages Section    
             */
            Route::group(['prefix' =>   'subpages' ], function(){
                Route::post('/edit',[
                    'as'    =>  'update.subpage.super',
                    'uses'  =>  'SubPagesController@update'
                ]);
                Route::post('/destroy',[
                    'as'    =>  'destroy.subpage.super',
                    'uses'  =>  'SubPagesController@destroy'
                ]);
            });
            Route::resource('subpages', 'SubPagesController', [
                'names' =>  [
                    'index'     =>  'all.subpages.super',
                    'create'    =>  'create.subpage.super',
                    'store'     =>  'store.subpage.super',
                    'edit'      =>  'edit.subpage.super'
                ],
                'only'  =>  [
                    'index','show','create','edit','store'

resources/views/blank.blade.php
@extends('layouts.app')

@section('title',$page->title)

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="row">
	<?php
		print($page->content);
	?>
</div>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts')
<script type="text/javascript">
	$(function(){
		$('form ').addClass(' form ');
		$('* input ').addClass(' form-control ');
		$('* textarea ').addClass(' form-control ');
	});
</script>
@endsection

resources/views/certificates.blade.php
@extends('layouts.app')

@section('title','Statistics')

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2"> 
		@if( $repo->countA( $certificates ) > 0 )
			<table class="table ">
			<thead>
				<th>#</th>
				<th>Course Name</th>
				<th>Marks</th>
				<th>Date</th>
				<th></th>
			</thead>
			<tbody>
			<?php $r = 1; ?>
			@foreach( $certificates as $cert )
				<tr>
					<td>{{ $r }}</td>
					<td><label class="label label-primary" style="font-size: 14px;">{{ ucfirst($repo->getCredit( $cert->credit_id )) }}</label></td>
					<td><label class="label label-primary" style="font-size: 14px;">{{ $repo->isAbove( $cert->marks )[1] }}%</label></td>
					<td><label class="label label-primary" style="font-size: 14px;">{{ $cert->created_at->diffForHumans() }}</label></td>
					<td>
						<a href="{{ url(route('viewcert',[$cert->id, $token])) }}" class="btn btn-block btn-sm btn-primary">
							View
						</a>
					</td>
				</tr>
			<?php $r++ ?>	
			@endforeach
			</tbody>
			</table>
		@else
		<h1 class="text-center">You don't have any Certificate</h1>
		@endif
		</div>
	</div>
</div>	
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts')
<script type="text/javascript">
	$(function(){
		$('form ').addClass(' form ');
		$('* input ').addClass(' form-control ');
		$('* textarea ').addClass(' form-control ');
	});
</script>
@endsection

resources/views/contact-us.blade.php
@extends('layouts.app')

@section('title',"Contact Us")

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="row">
	<form class="form-horizontal" action="{{ url(route('contact.us.post.web')) }}" method="post">
	{!! csrf_field() !!}
		<div class="col-sm-12">
			@if (session()->has('errors'))
			    <!-- Form Error List -->
			    <div class="alert alert-danger">
			        <strong>Whoops! Something went wrong!</strong>
			        <br><br>
			        <ul style="list-style: none;">
			            @foreach (session()->pull('errors') as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@elseif(session()->has('success'))
			    <div class="alert alert-success">
			        <strong>{{ session()->pull('success') }}</strong>
			        <br>
			    </div>
			@endif
		</div>
		<div class="form-group">
			<label for="inputName" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-7">
			  <input type="text" name="name" autofocus class="form-control" id="inputName" placeholder="Your Names" value="{{ old('name') }}" required>
			</div>
		</div>
		<div class="form-group">
			<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-7">
			  <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ old('email') }}" required>
			</div>
		</div>
		<div class="form-group">
			<label for="message" class="col-sm-2 control-label">Message</label>
			<div class="col-sm-7">
			  <textarea class="form-control" rows="3" name="message" id='message' placeholder="Your Suggestion, Problem or Opinion ">{{ old('message') }}</textarea>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-7">
			  <button type="submit" class="btn btn-primary">Send My Message</button>
			</div>
		</div>
	</form>	
</div>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts')
<script type="text/javascript">
	$(function(){
		$('form ').addClass(' form ');
		$('* input ').addClass(' form-control ');
		$('* textarea ').addClass(' form-control ');
	});
</script>
@endsection

resources/views/course.blade.php
@extends('layouts.app')

@section('title',$page->title)

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<h1>{{ ucfirst($course->course) }}</h1>
		<p>
			{{ ucfirst($course->summary) }}
		</p>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12">
	<h3 class="h3">Available Credits For This Course </h3>
		<?php $i = 0; ?>	
		<div class="row">
		@foreach($course->credit as $credit )
			@if($credit->active)
			    <?php $file = $page->getFile($credit->media_id) ?>
				<div class="col-sm-4">
					<div class="panel panel-default ">
						<div class="panel-heading">{{ $credit->title }}</div>
						<div class="panel-body" style="text-align: justify;" >
						{{ ucfirst($credit->summary) }}
						</div>
						<div class="panel-footer">
							<a href="{{ asset(url($file)) }}" target="__blank" class="btn btn-md btn-link pull-right">Read More</a>
							<br>
						</div>
					</div>
				</div>
			@endif
		@endforeach
		</div>
	</div>
</div>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts_t')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/1.5.458/pdf.min.js"></script>
<script type="text/javascript">
	PDFJS.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/1.5.458/pdf.worker.min.js";
</script>
@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/courses.blade.php
@extends('layouts.app')

@section('title',$page->title)

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<h1>All Our Courses and Credits</h1>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
		@foreach($page->content as $course )
			<table class="table col-xs-12 col-sm-12 col-md-12 col-lg-12 log" >
				<tbody class="" >
					<tr>
					    <tr> <a href="{{ url(route('course.show',$course->course)) }}"><h3>{{ ucfirst($course->course) }}</h3></a> </tr>
						<td class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
							<p>
								{{ ucfirst($course->summary )}}
							</p>
						</td>
					</tr>	
				</tbody>
			</table>
		@endforeach
		
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<center>{!! $page->content->links() !!}</center>
	</div>
</div>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/gallery.blade.php
<?php
  // Pagination Section
  $p = isset($_GET['p'])? $_GET['p'] : '1';

  $images = $page->content;
  $start = $p == 1 ? 0 : ($page->perpage - 1) + ($p - 1) ;
  $end =  $start + ($page->perpage - 1);
  $count = $page->all;
  $end = $end <= $count ? $end : $count - 1;
  $ko = isset($_GET['tk'])? '&tk='.$_GET['tk'] : '';

  //Token for delete images
  $token = "";  
  if(isset( $_GET['tk'] ))
    $token = $_GET['tk']
?>
@extends('layouts.app')

@section('title',$page->title)

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<section class="gallery-section">
  @if(\Auth::guard('admins')->check() && \Session::has('del-gal') && \Session::get('del-gal') === $token )
  <div class="row del-btn hidden ">
    <div class=" col-md-offset-5">
      <button class="btn btn-danger btn-md btn-flat" >Delete Selected Images</button>
    </div>
    <div class="clearfix">&nbsp;</div>
  </div>
  @endif
	<ul class="row">
    @if( isset($images[$end]) && $p <= $page->pages )
      @foreach(range($start, $end) as $value )
            @if( \File::exists( public_path().'/img/gallery/'.$images[$value] ) )
              <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                  <img class="img-responsive" src="{{ asset(url('/img/gallery/'.$images[$value])) }}">
                  @if(\Auth::guard('admins')->check() && \Session::has('del-gal') && \Session::get('del-gal') === $token )
                    <!-- <form action="{{ url(route('gallery.destroy')) }}"  method="post" class="form-destroy" > -->
                      <button type="button" class="btn btn-flat btn-block btn-xs btn-danger delete-image" value="{{ $images[$value] }}" style="margin-top: 3px;border-radius: 0px;" >Delete <span class="glyphicon glyphicon-arrow-up" style="font-weight: normal;font-size: xx-small;"></span></button>
                      <!-- <input type="checkbox" name ="images[]" value="{{ $images[$value] }}" class="pull-right checkbox">
                      <input type="hidden" name="tk" value="{{ $token }}" >
                      <input type="hidden" name="checkbox" value="1" > -->
                    <!-- </form> -->
                  @endif
              </li>
            @endif
      @endforeach
    @endif
	</ul>
  @if($page->pages > 1  )
	<nav>
	  <ul class="pager">
	    @if( $p > 1 )
        <li><a href="/gallery?p={{ ($p - 1).$ko  }}">Previous</a></li>
      @endif
      @if($page->pages > $p )
	     <li><a href="/gallery?p={{ ($p + 1).$ko  }}">Next</a></li>
      @endif
	  </ul>
	</nav>
  @endif
	<div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">         
          <div class="modal-body">                
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</section>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')
  <style>
      .gallery-section ul {         
          padding:0 0 0 0;
          margin:0 0 0 0;
      }
      .gallery-section ul li {     
          list-style:none;
          margin-bottom:25px;           
      }
      .gallery-section ul li img {
          cursor: pointer;
          box-shadow: 0px 0px 2px #999;
      }
      .modal-body {
          padding:5px !important;
      }
      .modal-content {
          border-radius:0;
      }
      .modal-dialog img {
          text-align:center;
          margin:0 auto;
      }
    .controls{          
        width:50px;
        display:block;
        font-size:11px;
        padding-top:8px;
        font-weight:bold;          
    }
    .next {
        float:right;
        text-align:right;
    }
      /*override modal for demo only*/
      .modal-dialog {
          max-width:500px;
          padding-top: 90px;
      }
      @media screen and (min-width: 768px){
          .modal-dialog {
              width:500px;
              padding-top: 90px;
          }          
      }
      @media screen and (max-width:1500px){
          #ads {
              display:none;
          }
      }
  </style>
@endsection

@section('scripts')
<script type="text/javascript" src='{{ asset(url("/plugins/gallery/photo-gallery.js")) }}' ></script>
<script type="text/javascript">
  $(function(){
    $('*.delete-image').on('click',function(e){
        var v = e.target.value;
        $.ajax({
          url  : "{{ url(route('gallery.destroy')) }}",
          type : 'POST',
          beforeSend : function(xhr){
            var token = "{{ csrf_token() }}";
            if(token){
              return xhr.setRequestHeader('X-CSRF-TOKEN',token);
            }
          },
          data : {
            image : v,
            checkbox : '0',
            tk : "{{ isset($token)? $token : '' }}"
          },
          success : function(data){
            //alert(data);
            window.location = "{{ url(route('gallery.index')) }}?p={{ $p }}";
            window.close();
          },
          error : function(error){
            console.log(error);
          }
        });
    });
    $('.checkbox').on('click', function(i){
      $('.del-btn').removeClass('hidden');
    });
    $('.del-btn').on('click', function(i){
      $('.form-destroy').submit();
    });
  });
</script>
@endsection

resources/views/nopayment.blade.php
@extends('layouts.app')

@section('title',"No Payment")

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
<div class="row">
<h1>Please You Have Not Payed </h1>
<br>
<span class='text-info text-lg'>Click <a href='{{ url("payments") }}'>Here to see payment methods</a> </span>

</div>
<div class="clear-fix">&nbsp;</div>
@endsection

@section('styles')

@endsection

@section('scripts')

@endsection

resources/views/register.blade.php
<?php
	function geterrors(){
		
		if(session()->has('errors')){
			$errors = session('errors');
			return $errors;
		}
		else
			return [];
	}

	function inputs($name = ''){
		// $oldInputs = @session()->pull('with')['oldInputs'];
		// if(isset($oldInputs)){
		// 	$input = $oldInputs[$name];
		// 	return $input;
		// }
		// else
			return "";
	}
?>
@extends('layouts.app')

@section('title',$page->title)

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-9">
			<h1>Register now to start your courses</h1>
	</div>
	<form role='form' action="{{ url(route('registration.store')) }}" method="post" enctype="multipart/form-data"  >
		<div class=" col-xs-12 col-sm-12 col-md-7 col-lg-7 responsive-table">
			{{ csrf_field() }}
				@if( geterrors() )
					@foreach( geterrors() as $error )
						<div class="alert alert-danger alert-dismissible">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							{{ $error }}
						</div>
					@endforeach
				@endif
			 	<table class="table col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
					<tbody>
						<tr>
							<td>Your First name</td>
							<td>
								<input type="text" required autofocus name="firstname" value="{{ old('firstname') }}" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs">

							</td>
						</tr>
						<tr>
							<td>Your Last name</td>
							<td>
								<input type="text" required name="lastname" value="{{ old('lastname') }}" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs">

							</td>
						</tr>
						<tr>
							<td>Sex</td>
							<td>
								<label class="checkbox-inline">
									<input type="radio" value="Male" name="gender"  checked>Male
								</label>
								<label class="checkbox-inline">
									<input type="radio" value="Female" name="gender">Female
								</label>
							</td>
						</tr>
						<tr>
							<td>Districts</td>
							<td>
								<select required class="form-control district" name="district">
									<option value="" disabled selected >Select Your District...</option>
									@foreach(\App\District::orderBy('district_name','asc')->get() as $sector )
									<option value="{{ $sector->id }}" > {{ $sector->district_name }} </option>
									@endforeach
								</select>
								<span class="text text-sm text-info">Use Mouse to select district</span>
							</td>
						</tr>
						<tr id="sector">
							<td>Sectors</td>
							<td>
								<select required class="form-control sector" name="sector" ></select>
							</td>
						</tr>
						<tr>
							
						</tr>
						<tr>
							<td>Your E-mail</td>
							<td><input type="email" required autocomplete="off" name="email" value="{{ old('email') }}" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs"></td>
						</tr>
						<tr>
							<td>Create your password</td>
							<td><input type="password" required name="password"  class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs"></td>
						</tr>
						<tr>
							<td>Confirm your password</td>
							<td><input type="password" required name="password_confirmation" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs"></td>
						</tr>
						<tr>
							<td class="col-sx-12 col-sm-12 col-md-3 col-lg-3">Your Proffessional</td>
							<td><input type="text" required name="proffessional" value="{{ old('proffessional') }}" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs"></td>
						</tr>
						
						<tr>
							<td>Your Phone Number</td>
							<td><input type="text" required autocomplete="off" maxlength="10" minlength="10" value="{{ old('telephone') }}"  name="telephone" class="form-control col-sx-12 col-sm-12 col-md-8 col-lg-8 inputs"></td>
						</tr>
					</tbody>
				</table>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 responsive-table">
			<table class="table col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
				<tbody>
					<tr>
						<td>Passport Photo</td>
						<td><input type="file" name="picture" id="filer_input" class="col-sx-12 col-sm-12 col-md-8 col-lg-8"></td>
					</tr>
					<tr>
						<td>Diplome</td>
						<td><input type="file" name="cv[]" id="filer_input2" multiple="multiple" class="col-sx-12 col-sm-12 col-md-8 col-lg-8"></td>
					</tr>
				</tbody>
			</table>
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 click page-header" >
				<button type="submit" class="btn btn-default register">Accept Registraion</button>
				<button type="reset" class="btn btn-default register pull-right">Cancel Registration</button>
			</div>
		</div>
	</form>
@endsection
<?php session()->forget('errors');  ?>
@section('styles')
<link rel="stylesheet" href="{{asset(url('plugins/jQuery.filer/css/jquery.filer.css'))}}" rel="stylesheet" />
<link rel="stylesheet" href="{{asset(url('css/site.plugins.css'))}}" rel="stylesheet" />
@endsection

@section('scripts')
<script src="{{ asset(url('plugins/jQuery.filer/js/jquery.filer.min.js?v=1.0.5')) }}"></script>  
<script src="{{ asset(url('js/register.js?v=1.0.5')) }}"></script>

<script type="text/javascript">
  $('#sector').hide();
  $('.district').on('click',function(e){
  	var v = $(this).val();
  	$.ajax({
  		url : '/getsector',
  		type : 'POST',
  		beforeSend : function(xhr){
  			var token = "{{ csrf_token() }}";
  			if(token){
  				return xhr.setRequestHeader('X-CSRF-TOKEN',token);
  			}
  		},
  		data : {
  			district : v
  		},
  		success : function(data){
  			$('.sector').html(data);
  			$('#sector').fadeIn();
  		},
  		error : function(error){
  			console.log(error);
  		}
  	});
  });
</script>
@endsection